#!/bin/bash
THRESH=4
if [ -d "/assets" ]; then
  TMP=$(mktemp --tmpdir=/assets -d --suffix=testpassgen)
else
  TMP=$(mktemp -d -t testpassgen.XXXXXX)
fi

./passgen -v > $TMP/testgen
#cat $TMP/testgen
ent -t $TMP/testgen |tail -n1 > $TMP/testgen.csv
#cat $TMP/testgen.csv
./tester.sh $TMP/testgen.csv $THRESH
rm -Rf $TMP
